spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pw45s
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

minio:
  endpoint: http://localhost
  port: 9000
  accessKey: minioadmin
  secretKey: minioadmin
  secure: false
  bucketName: my-default-bucket
  imageSize: 5242880       # 5MB (ajuste conforme necessário)
  fileSize: 104857600      # 100MB (ajuste conforme necessário)
